# ===============================
# Currency API
# ===============================
currency.api.base-url=https://api.frankfurter.dev/v1

# ===============================
# World Bank API
# ===============================
worldbank.api.base-url=https://api.worldbank.org/v2

# ===============================
# Weather API
# ===============================
weather.api.base-url=https://api.example-weather.com
weather.api.api-key=api_key_here

# ===============================
# Timezone API
# ===============================
timezone.api.base-url=https://api.example-time.com
timezone.api.api-key=api_key_here

# ===============================
# Spring Application
# ===============================
spring.application.name=currency-global-time-hub
