spring.application.name=currency-global-time-hub


// using exchangerate.host, provides free exchange rate data without requiring an API key
currency:
  api:
    base-url: https://api.exchangerate.host
